"""adição modulo de fluxo de caixa

Revision ID: bda15847b1ee
Revises: e66275f84830
Create Date: 2020-03-08 20:57:40.941330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda15847b1ee'
down_revision = 'e66275f84830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lancamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimentacao', sa.String(length=1), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('data_lancamento', sa.Date(), nullable=False),
    sa.Column('data_prevista', sa.Date(), nullable=False),
    sa.Column('data_efetivacao', sa.Date(), nullable=False),
    sa.Column('valor_previsto', sa.Float(precision=15, asdecimal=2), nullable=False),
    sa.Column('valor_realizado', sa.Float(precision=15, asdecimal=2), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lancamentos')
    # ### end Alembic commands ###
