"""correcao na nomeclatura dos campos

Revision ID: dd1ba9208f3f
Revises: 17262c68cc6b
Create Date: 2020-03-10 12:43:20.153082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd1ba9208f3f'
down_revision = '17262c68cc6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lancamentos', sa.Column('contas_id', sa.Integer(), nullable=False))
    op.drop_constraint('lancamentos_ibfk_1', 'lancamentos', type_='foreignkey')
    op.create_foreign_key(None, 'lancamentos', 'contas', ['contas_id'], ['id'])
    op.drop_column('lancamentos', 'conta_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lancamentos', sa.Column('conta_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lancamentos', type_='foreignkey')
    op.create_foreign_key('lancamentos_ibfk_1', 'lancamentos', 'contas', ['conta_id'], ['id'])
    op.drop_column('lancamentos', 'contas_id')
    # ### end Alembic commands ###
