"""adição modulo de fluxo de caixa

Revision ID: e66275f84830
Revises: 9fc8e1d68ca2
Create Date: 2020-03-08 09:11:22.227299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66275f84830'
down_revision = '9fc8e1d68ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contas')
    # ### end Alembic commands ###
