"""commit incial

Revision ID: 125f546ab7d0
Revises: 
Create Date: 2020-03-21 14:28:41.979791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125f546ab7d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=16), nullable=False),
    sa.Column('data_nasc', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Float(precision=15, asdecimal=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('forma_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('contas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contas_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lancamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimentacao', sa.String(length=1), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('data_lancamento', sa.Date(), nullable=False),
    sa.Column('data_prevista', sa.Date(), nullable=False),
    sa.Column('data_efetivacao', sa.Date(), nullable=True),
    sa.Column('valor_previsto', sa.Float(precision=15, asdecimal=2), nullable=False),
    sa.Column('valor_realizado', sa.Float(precision=15, asdecimal=2), nullable=True),
    sa.Column('contas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contas_id'], ['contas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmado', sa.Boolean(), nullable=False),
    sa.Column('ausencia', sa.Boolean(), nullable=True),
    sa.Column('data_agenda_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_agenda_fim', sa.DateTime(), nullable=False),
    sa.Column('valor_servico', sa.Float(precision=15, asdecimal=2), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('forma_pagamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['forma_pagamento_id'], ['forma_pagamento.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    from app import db
    from app.modulos.user.models import User

    u = User()
    u.username = 'Admin'
    u.email = 'admim@admin.com'
    u.set_password('admin123')
    db.session.add(u)
    db.session.commit()

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agenda')
    op.drop_table('lancamentos')
    op.drop_table('forma_pagamento')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('servico')
    op.drop_table('contas')
    op.drop_table('cliente')
    # ### end Alembic commands ###
